name: Bug Report
description: Report a bug in the Causeway

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which part of the Causeway scope is affected by this bug?
      options:
        - animations
        - bazel
        - common
        - compiler-cli
        - compiler
        - core
        - elements
        - forms
        - language-service
        - localize
        - platform-browser-dynamic
        - platform-browser
        - platform-server
        - router
        - service-worker
        - upgrade
        - zone.js
        - Don't know / other
      multiple: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A concise description of what you are experiencing.
      placeholder: Tell us what you see!

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshots
    attributes:
      label: Add ScreenShots
      description: Add sufficient screenshots to explain your issue.

  - type: dropdown
    id: devices
    attributes:
      label: On which device are you experiencing this bug?
      multiple: true
      options:
        - Android
        - iPhone
        - Linux
        - Chrome
        - Windows

  - type: textarea
    id: other
    attributes:
      label: Anything else?
